# Generated by Django 4.1.1 on 2022-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_email_person_gender_person_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
